### ISSUE TITLE
代表者をやりたいです

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/techbookfest#1]
[技術書典](https://techbookfest.github.io/)に参加するには、誰かが代表者になってサークルの参加申込を行なう必要があります。

言い出しっぺの法則で自分（@MakeNowJust）がやりたいのですが、こういったことにノウハウのある人は教えていただけると嬉しいです。

**Comment by rosylilly** [comment]
文フリの経験から
- 代表者は基本申し込みとか事務局のやり取りするのがメイン、そんなにすることない
- サークルチケット忘れたりすると完全に詰むので気をつけましょう
- 販売時の棚のレイアウトとかは気合いれれば入れるほど強いので気合は入れたほうが Good です
  - けど別に代表者の仕事ってわけじゃない……
- 印刷所への発注などは代表者が行うほうが懸命です
  - 大抵の同人サークル向け出版社ならサークルブースに直配送してくれます

**Comment by makenowjust** [comment]
ありがとうございます。参考にします。

**Comment by makenowjust** [comment]
人数が集まりそうだったので自分を代表者にしてサークル名「Crystal-JP」で登録しました。大丈夫だったでしょうか？

**Comment by makenowjust** [comment]
開きっぱなしにするのも微妙なのでcloseします。
