### ISSUE TITLE
参加できそうな人

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/techbookfest#2]
Crystalについての記事を複数集めてまとめた同人誌を作りたいと思います。（異論がある方は何か書いていただいても構いません）

何か書けそう・書いてみたい、という方はコメントしていってください。

記事の方向性具体的にはまだ何も決まっていないので、ここでのコメントを見て逐次考えていきたいと思っています。

**Comment by pine** [comment]
:+1:

**Comment by nob-suz** [comment]
Qiita の記事をリファインするでもいいですか？

**Comment by masak1yu** [comment]
参加希望です。

**Comment by makenowjust** [comment]
@nob-suz 

> Qiita の記事をリファインするでもいいですか？

全然okだと思います。

**Comment by pacuum** [comment]
参加してみたいです

**Comment by arcage** [comment]
何かお役に立てることがあれば。

**Comment by makenowjust** [comment]
@pine613 @nob-suz @ucmsky @pacuum @arcage

参加が確定したので少しずつ話しを進めていきます。

本の構成として、最初にCrystalの軽い紹介（言語の目標とか構文など）があって、そのあとに各々の記事が続いて、最後にCrystalの展望についての文章があるものを想定しているのですけど、紹介とか展望を書いてくださる方はいますか？　紹介と展望は別の方でも構いません。むしろ別の方のほうがいいです。紹介・展望を書く人は別の記事は書かなくてもいいかな、と考えているのですけれど、現実的に書けるのであれば書けばいいと思います。

それと、各人どんな内容になりそうかコメントしてください。

**Comment by masak1yu** [comment]
私担当範囲だと、
マクロ回り(qiita投稿内容がメイン、加筆あり)
frostの現時点でできること（第3回勉強会の内容の続き）
herokuへのデプロイ（ビルドパックの使い方）

あたりは纏めたいです。

**Comment by arcage** [comment]
Qiitaで書いた内容（＋α）をブラッシュアップして，数値や文字列，配列，ハッシュ，シンボルなど標準的なオブジェクトを中心にRubyからの移行で躓きそうな部分をピックアップしてみたいと思っています。

個人的に，
- １記事のボリューム的な目安
- 記事を書く際のフォーマット

あたりが気になってます。

**Comment by pine** [comment]
以下の話なら書けそうです。
- crenv 関係
- Crystal を実際に使ってウェブアプリを作る話
- Crystal で CLI ツールを作る話

**Comment by makenowjust** [comment]
みなさんありがとうございます。

@arcage 

> 個人的に、
> - １記事のボリューム的な目安
> - 記事を書く際のフォーマット

ボリュームは、人数を考えると最低でも一人4ページくらい書けば本としてまとまると思いますが、上限はとくに考えてません。
フォーマットはQiitaの記事を下敷きにするものが多いので自然にMarkdownになりそうなのですが「もっと他のフォーマットでいいのがあるぞ」って方は教えてくださると嬉しいです。

**Comment by nob-suz** [comment]
みなさん　こんばんは
参加希望します
・生い立ち記事　Qiita　Crystal 言語の 2015年を振り返ってみて＋Manas社1月生い立ち記事＋2016年の進展

全体構成を目次っぽく羅列すると、整理合意が速いので、仮にこんな感じかな、というのをまず書きます。　数字は章段落番号ではなく、修正指摘しやすいトレース番号です。上書き修正ください

せっかくなので、メモリアル的、後でレアものになるとうれしいという希望を込めて

１．巻頭言　CrystalのGranpa　Matzさんにお願いしてみる
２．発巻に寄せて　　Crystalの作者　Wajiさん　Aryさんに　お願いしてみる
３．初めに　MakenowJust　さん
４．Crystalの軽い紹介（言語の目標とか構文など）
５．Crystal言語の生い立ちと登場人物紹介　　Nob　（Qiita文修正）
６．７．８．９．10．．．．それぞれの記事

1X．　Crystalで作成したアプリの作者にメッセージ下さいとお願いしてみて、集まった文　掲載
　　　（各1ページ　手書きのカメラ画像を送ってもらう、またはメッセージ　とサイン
2X．　最後にCrystalの展望について　　　どなたか、またはAryさんにお願い

お願いするルートは、メール、Ｇｉｔ、Google　でダメもとで私がするのもかまいません
　1Xのアプリの作者など海外の登場者へのお礼は、現物か電子ファイルでどうかと

あいかわらずの妄想ですが、たたき台にどうぞしてください

**Comment by makenowjust** [comment]
nobさんの構想は面白いのですが、全てを実現するのはやや難しそうです（例えば `1X` は、そんなにたくさん誰が連絡するんだって話になるし、返事があった人が一人くらいだったときなんかはすごく扱いに困ります）。ただ、MatzさんやAryさんに一筆したためてもらうのは面白いと思うので、なるべく早めに連絡して確認を得ておきたいと思います。

また、みなさん全体の構成を気にして書き出せていないような気がします。自分がそんな雰囲気を最初に作ってしまったせいかもしれません。これは自分の経験なのですが、各々の書きたいものを持ち寄って一冊にまとめれば、案外と本として読めるものになります。特に今回の場合は一つ通ったテーマがあるので（この場合はCrystalについて、ということ）、それさえ守って気楽にやればかなりいい出来の物になるはずです。

一番困るのは、原稿が上がらなくて本が印刷できなくなって、技術書典に参加できなくなることです。ぶっちゃけ早く書きさえすれば全体の構成の擦り合わせなんていくらでもすることができますし、Crystalの紹介や展望も手の空いてる人で割り振って書くことができます。ともかく書いてください。原稿が無ければ本は作れません。

最後にボクは、今はMarkdownからpdfに変換する仕組みをどうするかを模索しているところです。他にも色々考えることがあるので、何か記事を書けるかは未定としておきます。

**Comment by 5t111111** [comment]
ちょっと原稿を新規に書く余裕はないんですが、つい先日リリースされた 0.16.0 のコンパイラの改善につながる話として[ココ](http://crystal-lang.org/2016/05/05/crystal-0.16.0-released.html)でも言及されている去年のアドベントカレンダーの [Ary さんの記事の翻訳](http://fiveteesixone.lackland.io/2015/12/28/the-future-of-crystal/)なら提供できます。

もう半年前とかのものだし季節ものってことでかなり微妙ですけど、文字数的にもそこそこあるし、物語風でなかなか読ませる内容なので掲載する記事の多様性に膨らみを持たせられるような気もするし、何より直近のでかい breaking changes の背景でもあるのでナシではないかなーと。

リファインするとしても不要なところを消すくらいしかしないつもりなので markdown の原稿はもうほぼできてるようなもんだから、原稿が足りなそうだからそれでもオッケー、とかのときはいつでも言ってください。そうなれば Ary さんへの掲載の可否の確認とかはこっちでやります。

**Comment by rhysd** [comment]
今から参加って可能でしょうか？

せっかく [Crisp](https://github.com/rhysd/Crisp) を作ったので，Crystal で [Make a Lisp](https://github.com/kanaka/mal) の Lisp 処理系実装の解説を書いてみたいです（10段階のステップに分かれているので，ステップいくつまで書くかは分量と時間に応じてという感じにしたいです）．

**Comment by makenowjust** [comment]
@rhysd 本は厚い方がいいので、いいんじゃないかと思います。

**Comment by rhysd** [comment]
@MakeNowJust ありがとうございます．やりとりは Slack のどこかのチャンネルがメインでしょうか？

**Comment by masak1yu** [comment]
@rhysd slackの
https://crystal-jp.slack.com/archives/techbookfest
で話し合っております（遅レスすみません

**Comment by rhysd** [comment]
@ucmsky 了解です :+1:

**Comment by makenowjust** [comment]
@pacuum 記事って書いてますか？

**Comment by makenowjust** [comment]
@rhysd @pine @ucmsky @arcage @nob-suz

すみません、記事の冒頭に自分の名前と簡単な紹介的なものを一段落くらいで入れてもらえますか？
