### ISSUE TITLE
何を頒布するか？

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/techbookfest#3]
実際に印刷したものを頒布するのか、CDとかDVDとかUSBにpdfなりを頒布するのか、という話です。技術書典的にはどちらでもいいみたいです。

**Comment by makenowjust** [comment]
個人的には印刷した本を作ってみたいな、という気持ちがあります。

**Comment by nob-suz** [comment]
時間差を作って、後でeBOOK有料ダウンロードもありですかね？、
著作権料はCrysta-JPでプールして、普及に使う、もありですが、
Bountysourceに寄付もありですね

**Comment by rosylilly** [comment]
記事を書く時間はとれなさそうなんですが、印刷したいんであれば製本データ作るのはお手伝いします

**Comment by makenowjust** [comment]
@rosylilly 了解です（そのコメント #2 の方がよかったのでは…）

@nob-suz 後で公開するなら（個人的には）フリーにしたいです。会場で頒布するのはあくまで印刷費を回収できたらいいな、くらいのつもりで。
