### ISSUE TITLE
参加費をどうするか？

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/techbookfest#4]
参加費が5000円ほどかかります。これをどうしましょうか？

参加者で割る？

**Comment by nob-suz** [comment]
本の製版費用と部数はどんなもんですかね？　どなたか経験あります？　それが主体になりそうな　部数は50部くらい？

**Comment by rosylilly** [comment]
ページ数や印刷所、印刷クオリティや紙の指定の問題があるので、一概にこの程度、とは言えないんですが、大体3〜4万円程度かな > 製版費用(部数50の想定)

発行部数を増やす分にはほとんど誤差みたいなもんですが、ページ数がずれると値段がガクッと変わるので、ある程度ページ数は見積もっておいたほうが良いです。
(ex: 1人6pで5人で30p)

まぁ、イベントで持ち込んで技術書売るとして20部捌ければ儲けモンぐらいの気持ちでいた方がいいし、余ると在庫を抱えることになるので、50部ぐらいがおすすめです(あとから Stores.jp とか使って通販するってんならお手伝いします)。

印刷どこまでこだわるかなどの問題もあるので、おさいふや作りたいものにあわせて相談ですかねー。
