### ISSUE TITLE
ファイル構成

### ISSUE THREAD

**Issue by masak1yu** [crystal-jp/techbookfest#7]
とりあえずmarkdownで行くか、re:viewで行くかは暫定的にmarkdownでと考えていますが、ファイル構成は以下の形を仮のものとしたいと思います。
- crystal-techbook-cover.md 表紙
- crystal-techbook-index.md 目次
- crystal-techbook-maintext.md 本文

各章のテキストは書きあがるごとにcrystal-techbook-maintext.mdへPRを行い、レビュー後にマージを行いながらにしましょうか。

**Comment by makenowjust** [comment]
maintextにみんなでコミットしていくのはマージしていくのが面倒すぎるので、テキストの一つにまとめるのはビルドシステムに任せて、

```
techbookfest/
  pine/
    main.md
  ucmsky/
    main.md
  <各ユーザー名>/
    main.md
```

みたいに、`<各ユーザー名>/` ディレクトリの中にMarkdownを置いていく方がいいと思います。（そのつもりでずっと考えていたのですけど伝えていなくてごめんなさい）

**Comment by masak1yu** [comment]
了解しました。印刷やPDF化する場合は、最終的に1個のファイルに纏まるのはシステム的にやってくれる感じですか？
（編集しやすいのがあればその形にしようかな、と思って1個ファイルを考えていたもので）
